### ISSUE TITLE
gamma cohort

### ISSUE THREAD

**Issue by fczuardi** [fczuardi/fellowship#11]
### Current cohort:

This issue is for listing the links for the notes and recordings of the 3rd iteration of the Falafel Fellowship program starting in **June 13, 2023**.

#### Current fellows:
- @fczuardi 
- @mquasar
- @GabrielSoga

#### to-do:
- [x] welcome email w/ terms for the participants
- [x] pay the stipends
- [x] schedule the meetings

### Previous cohorts:
- #7 alpha
- #8 beta

**Comment by fczuardi** [comment]
# 35

## summary

- welcome 2 new cohorts
- continued the work on https://github.com/getAlby/lightning-browser-extension/pull/2445 ( issue https://github.com/getAlby/lightning-browser-extension/issues/2435 )
- organized the people rotation in trios for the next sessions

## pre-meeting links

- Room A: https://meet.google.com/gsz-kypk-zqd
- ~Room B: https://meet.google.com/yzw-whkc-zcg~
- Notes: https://docs.google.com/document/d/15yw5sUeS-ih2_vX2nhnG59HFFFaGxrt4lTtWy03ufI4/edit
- Whiteboard: https://excalidraw.com/#room=xc7ahu72jqa5hpsv5blx,cP50Cpt4mzDOqQaXWFpyrJ

**Comment by fczuardi** [comment]
4 people, combination of trios:

- Mon: @fczuardi @mquasar @gabrielsoga
- Tue: @fczuardi  @marlacabral @mquasar
- Wed: @fczuardi @marlacabral @gabrielsoga
- Thu: @mquasar @marlacabral @gabrielsoga

**Comment by fczuardi** [comment]
# 36

## summary

- setup of Soga's environment
- debugged and reproduced issue https://github.com/getAlby/lightning-browser-extension/issues/2462

## meet
Work Session #36
Wednesday, June 14 · 9:30 – 11:30pm
Time zone: America/Sao_Paulo
Google Meet joining info
Video call link: https://meet.google.com/gsz-kypk-zqd

**Comment by fczuardi** [comment]
# 37

## summary
- Marcos and Soga browsed new issues
- https://github.com/getAlby/lightning-browser-extension/issues/2489 looked interesting, we were able to reproduce on Zuardi's machine
- After understanding the issue we started trying different approaches to trick Firefox to not autocomplete two different password fields with the same suggestion

## meet
Work Session #37
Thursday, June 15 · 9:30 – 11:30pm
Time zone: America/Sao_Paulo
Google Meet joining info
Video call link: https://meet.google.com/gsz-kypk-zqd

**Comment by fczuardi** [comment]
# 38

Work Session #38
Monday, June 19 · 9:30 – 11:30pm
Time zone: America/Sao_Paulo
Google Meet joining info
Video call link: https://meet.google.com/gsz-kypk-zqd

**Comment by fczuardi** [comment]
# 39

## meet 

Work Session #39
Tuesday, June 20 · 9:30 – 11:30pm
Time zone: America/Sao_Paulo
Google Meet joining info
Video call link: https://meet.google.com/gsz-kypk-zqd

**Comment by fczuardi** [comment]
# 40

## meet

Work Session #40
Wednesday, June 21 · 9:30 – 11:30pm
Time zone: America/Sao_Paulo
Google Meet joining info
Video call link: https://meet.google.com/gsz-kypk-zqd

**Comment by GabrielSoga** [comment]
# 41
 ## meet
 Work Session #41
 Wednesday, June 22 · 9:30 – 11:30pm
 Time zone: America/Sao_Paulo
 Google Meet joining info 
 Video call link: https://meet.google.com/gsz-kypk-zqd

**Comment by fczuardi** [comment]
# 42

## meet

Work Session #42
Monday, June 26 · 9:30 – 11:30pm
Time zone: America/Sao_Paulo
Google Meet joining info
Video call link: https://meet.google.com/gsz-kypk-zqd

**Comment by fczuardi** [comment]
# 43
